
source'https://github.com/leshiguang/cocoapods.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

platform :ios, '8.0'

target 'LSBluetoothSDK_Demo_iOS_Example' do
  pod 'LSBluetoothSDK_Demo_iOS', :path => '../'

  target 'LSBluetoothSDK_Demo_iOS_Tests' do
    inherit! :search_paths
    pod 'LSBluetoothSDK_iOS','1.4.6'
    pod 'LSNetworkingModule', '2.1.8'
    
    
  end
end
